### ISSUE TITLE
Add a license!

### ISSUE THREAD

**Issue by lionkor** [CPunch/PowToy#1]
hey! I'd love to contribute (if you allow that). I suggest you add a license if you want contributions!

**Comment by CPunch** [comment]
sorry for the late response! I licensed the project under the MIT license in [this commit](https://github.com/CPunch/PowToy/commit/db6e68dd3d533cf7f0080e2080f13fcb82db12b2)

and yes! contributions would be greatly appreciated!

**Comment by lionkor** [comment]
Awesome, thank you!
